package be.ugent.vopro5.backend.businesslayer.businessentities.models;

import java.time.LocalDateTime;
import java.util.Set;
import java.util.UUID;

import static be.ugent.vopro5.backend.businesslayer.businessentities.validators.Validators.notNull;

/**
 * Business entity representing an event generated by Waze
 */
public class WazeEvent extends Event {
    private static final EventPublisher EVENT_PUBLISHER = new WazeEventPublisher();

    private final UUID wazeUUID;

    /**
     * create a new waze event
     * @param identifier
     * @param location
     * @param active
     * @param publicationTime
     * @param lastEditTime
     * @param description
     * @param jams
     * @param eventType
     * @param relevantForTransportationTypes
     * @param wazeUUID
     */
    public WazeEvent(UUID identifier, LatLon location, boolean active, LocalDateTime publicationTime, LocalDateTime lastEditTime, String description, Set<Jam> jams, EventType eventType, Set<TransportationType> relevantForTransportationTypes, UUID wazeUUID) {
        super(identifier, location, active, publicationTime, lastEditTime, description, jams, eventType, EVENT_PUBLISHER, relevantForTransportationTypes);
        notNull(wazeUUID, "Waze UUID can not be null");
        this.wazeUUID = wazeUUID;
    }

    public UUID getWazeUUID() {
        return wazeUUID;
    }
}
